---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: dotnet-hello-world
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~1.0
spec:
  releaseName: dotnet-hello-world
  chart:
    git: https://github.com/devopslifter/demo-app
    ref: main
    path: charts/dotnet-hello-world
    secretRef:
      name: git-https-credentials
  values:
    image:
      repository: devopslifter/hello-appvia-demo
      tag: 1.0.1
    ingress:
      hosts:
      - host: hello.demos.kore.appvia.io
        paths:
        - /
      tls:
      - hosts:
        - hello.demos.kore.appvia.io
        secretName: dotnet-hello-world-tls
