---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: dotnet-hello-world
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: dotnet-hello-world
  chart:
    git: https://github.com/devopslifter/demo-app
    path: charts/dotnet-hello-world
    ref: main
    secretRef:
      name: git-https-credentials
  values:
    image:
      repository: devopslifter/hello-appvia-demo
      tag: dev-fd0cd294e1319e2ecdcc01d54b7817e413e6471a
    replicaCount: 1
