apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: dotnet-hello-world
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: dotnet-hello-world
  chart:
    git: https://github.com/devopslifter/demo-app
    path: charts/dotnet-hello-world
    ref: main
    secretRef:
      name: git-https-credentials
  values:
    ingress:
      enabled: false
    image:
      repository: devopslifter/hello-appvia-demo
      tag: dev-69958b1993ced8e490ab8a448f62d1444758535d
    replicaCount: 1